<?xml version="1.0" encoding="UTF-8"?>
<definitions name="service" targetNamespace="http://services.service.brrd.com/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:tns="http://services.service.brrd.com/" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://services.service.brrd.com/" schemaLocation="Service_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="movimientosPrestamo">
    <part name="MovimientosPrestamoRequest" type="tns:movimientosPrestamoRequest">
    </part>
  </message>
  <message name="movimientosPrestamoResponse">
    <part name="Response" type="tns:serviceResponse">
    </part>
  </message>
  <portType name="ImovimientosPrestamoRequest">
    <operation name="movimientosPrestamo">
      <input message="tns:movimientosPrestamo" wsam:Action="http://services.service.brrd.com/ImovimientosPrestamoRequest/movimientosPrestamoRequest">
    </input>
      <output message="tns:movimientosPrestamoResponse" wsam:Action="http://services.service.brrd.com/ImovimientosPrestamoRequest/movimientosPrestamoResponse">
    </output>
    </operation>
  </portType>
  <binding name="movimientosPrestamoImplPortBinding" type="tns:ImovimientosPrestamoRequest">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="movimientosPrestamo">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal" namespace="http://services.service.brrd.com/"/>
      </input>
      <output>
        <soap:body use="literal" namespace="http://services.service.brrd.com/"/>
      </output>
    </operation>
  </binding>
  <service name="service">
    <port name="movimientosPrestamoImplPort" binding="tns:movimientosPrestamoImplPortBinding">
      <soap:address location="http://172.22.30.34:9082/DEV/API/2.0/MovimientosPrestamo/service"/>
    </port>
  </service>
</definitions>
