<?xml version="1.0" encoding="UTF-8"?>
<definitions name="service" targetNamespace="http://services.service.brrd.com/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:tns="http://services.service.brrd.com/" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://services.service.brrd.com/" schemaLocation="ValidaCuentasMancomunadas_WS.xsd"/>
    </xsd:schema>
  </types>
  <message name="ValidarResponse">
    <part name="Response" type="tns:serviceResponse">
    </part>
  </message>
  <message name="Validar">
    <part name="ServiceRequest" type="tns:validarRequest">
    </part>
  </message>
  <portType name="IValidarRequest">
    <operation name="Validar">
      <input message="tns:Validar" wsam:Action="http://services.service.brrd.com/IValidarRequest/ValidarRequest">
    </input>
      <output message="tns:ValidarResponse" wsam:Action="http://services.service.brrd.com/IValidarRequest/ValidarResponse">
    </output>
    </operation>
  </portType>
  <binding name="ValidarImplPortBinding" type="tns:IValidarRequest">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="Validar">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal" namespace="http://services.service.brrd.com/"/>
      </input>
      <output>
        <soap:body use="literal" namespace="http://services.service.brrd.com/"/>
      </output>
    </operation>
  </binding>
  <service name="service">
    <port name="ValidarImplPort" binding="tns:ValidarImplPortBinding">
      <soap:address location="http://172.22.30.34:9082/UAT/API/2.0/ValidaTransaccionInterbancariaMancomunada/service"/>
    </port>
  </service>
</definitions>
